name: Release Obsidian Plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Build plugin
        run: |
          npm ci
          npm run build

      - name: Check build outputs
        run: |
          ls -la main.js manifest.json styles.css

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release create "$tag" \
            --title="$tag" \
            --draft \
            --notes "Plugin release $tag

          Files included:
          - \`main.js\` - Plugin code
          - \`manifest.json\` - Plugin manifest  
          - \`styles.css\` - Plugin styles

          To install manually, download these files and place them in your vault's \`.obsidian/plugins/obsidian-api/\` directory." \
            main.js manifest.json styles.css
